name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build with Cargo
        run: cargo build --release --verbose

      - name: Run unit tests
        run: cargo test --release --verbose --bin wsx

      - name: Run e2e tests
        run: cargo test --release --verbose --test e2e_cli

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Run Formatter Check
        run: cargo fmt --all --check
